### ISSUE TITLE
CLI invocation crashes

### ISSUE THREAD

**Issue by z3rone** [diogobor/Scout#10]
OS: Windows 10
Scout: 1.6.1

When running scout via CMD a new window opens for less than a second and then crashes. Running a screen recording I can see some logs (attached screenshot). The GUI runs without problems so far.

Steps to reproduce:

1. Download dataset PXD052022
2. Move all raw files to a RAWs folder
3. Create a sub-folder out-cli
4. Export the default search and and post-processing configs to the PXD052022 folder
5. Add these parameters to the `Scout_search_params.json`:
```
  "RawPath": "E:\\\\PXD052022\\RAWs",
  "FastaFile": "E:\\\\PXD052022\\4000-search.fasta",
  "OutputFolder": "E:\\\\PXD052022\\out-cli",
```
6. Run `E:\PXD052022>scout -search Scout_search_params.json Scout_post_processing_params.json`

<img width="807" alt="image" src="https://github.com/user-attachments/assets/1ea1dbd3-ea8f-4520-b4ac-e011fa6a1ef8">

**Comment by diogobor** [comment]
Hello,

In "E:\\\\PXD052022\\out-cli" a scout_log.txt has been created. This file contains all record about the search. Could you send us this file to check what happened?

Best regards,
Diogo

**Comment by z3rone** [comment]
The folder remains empty after crash unfortunately

**Comment by z3rone** [comment]
The post-processing parameters are these:
```
{
  "CSM_FDR": 0.01,
  "ResPair_FDR": 0.01,
  "PPI_FDR": 0.01
}
```

**Comment by diogobor** [comment]
We fixed the bug.
Thanks for evaluating Scout.

Best,
Diogo

**Comment by z3rone** [comment]
I found the cause of my problems. I was not expecting that the RawPath, OutputFolder and FastaFile would already be defined as null in the exported JSON. I just prepended the parameter to the JSON myself. Because of that the logfile also wasn't placed in the output path but the root path of the partition.

**Comment by z3rone** [comment]
it might be a nice feature to have the CMD stay open after crash and hint the path of the log file or something similar
