### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by Heisenburger2020** [diogobor/Scout#2]
Dear Sir/Madam,

I am Jiale Zhao, a Ph.D. student at the Institute of Computation in China.

I have met an error when running scout on Juri's(2021) dataset(DSSO). Would you be so kind to tell me how to solve this?

The error and parameter are as follows:

![error](https://github.com/diogobor/Scout/assets/65890878/21ab1364-cc4a-4e15-9abc-6082ee3ce37f)

{
  "BDP_Mode": false,
  "MSFileExtension": ".mgf",
  "PPMMS1Tolerance": 3.0,
  "PPMMS2Tolerance": 5.0,
  "PerformShotgunSearch": false,
  "PerformCleaveXLSearch": true,
  "SaveSpectraToResults": false,
  "MaxQueryResults": 4,
  "MinPepLength": 6,
  "MaxPepLength": 60,
  "MinPepMass": 600.0,
  "MaxPepMass": 6000.0,
  "FastaFile": "C:\\Users\\10076\\Desktop\\scout\\uniprot-k12-filtered-proteome_UP000000625.fasta",
  "RawPath": null,
  "AddMinusOneIsotope": false,
  "CarbonIsotopeShift": 1.0033548,
  "IsotopicPossibilitiesPrecursor": 1,
  "MiscleavageNum": 2,
  "Enzyme": {
    "Name": "Trypsin",
    "CTerminus": true,
    "Sites": "KR",
    "BlockedBy": "P"
  },
  "EnzymeSpecificity": 0,
  "MaximumVariableModsPerPeptide": 3,
  "StaticModifications": [
    {
      "MassShift": 57.02146,
      "Name": "Carbamidomethyl",
      "IsCTerm": false,
      "IsNTerm": false,
      "IsVariable": false,
      "TargetResidues": "C",
      "ModIndex": 1
    }
  ],
  "VariableModifications": [
    {
      "MassShift": 15.9949,
      "Name": "Oxidation of Methionine",
      "IsCTerm": false,
      "IsNTerm": false,
      "IsVariable": true,
      "TargetResidues": "M",
      "ModIndex": 2
    }
  ],
  "ExtraAminoacids": null,
  "SearchLoopLinks": true,
  "IonPairMaxCharge": 2,
  "CXLReagent": {
    "Name": "DSSO",
    "LightTag": "Light",
    "LightFragment": 54.01056468,
    "HeavyTag": "Heavy",
    "HeavyFragment": 85.98263585,
    "WholeTag": "Full",
    "WholeMass": 158.00376533,
    "DeltaShift": 31.972071169999992,
    "Targets": "K",
    "TargetNTerm": true
  },
  "FullPairsOnly": false,
  "PairFinderPPM": 5.0,
  "MinBinMZ": 200.0,
  "MaxBinMZ": 1800.0,
  "BinSize": 0.02,
  "Offset": 0.0,
  "ScoreFunction": 1,
  "MS2NormalizationTypes": 2,
  "NormalizationWindowWidth": 80.0,
  "NormalizationWindowPeaksKept": 13,
  "AddPrecursorToDotProduct": false,
  "AddIonPairsToDotProduct": false,
  "ApplyMZRangeWeighting": false,
  "ReorderCleaveCandidateScores": true,
  "RemoveIonPairsFromExperimentalMS": true,
  "RemovePrecursorFromExperimentalMS": true,
  "ReorderingMethod": 0,
  "ReorderingCombinatorialDepthHeavy": 3,
  "ReorderingCombinatorialDepthLight": 2,
  "FastaBatchSize": 30000,
  "ParallelPSMs": true,
  "QueryBatches": null,
  "MergeDatabase": false,
  "MethionineInitiator": true,
  "AddDecoys": true,
  "AddContaminants": true,
  "DontShowContaminants": true,
  "DecoyTag": "Reverse",
  "DecoyGenerationMode": 0,
  "AddUnlabelledDecoys": false,
  "UnlabelledDecoyTag": "Unlabelled",
  "OffsetUnlabelledDecoy": true,
  "OffsetUnlabelled": 2,
  "UnlabelledDecoysGenerationMode": 4,
  "AddLocusStringToPeptides": true,
  "DeconvolutionForPairSearching": true,
  "DeconvolutionForMSScoring": false,
  "SilacSearch": false,
  "SilacHybridMode": false,
  "SilacGroups": [
    {
      "GroupName": "Heavy",
      "GroupAminoacids": [
        {
          "TargetResidue": "K",
          "MassShift": 8.0141988131999
        },
        {
          "TargetResidue": "R",
          "MassShift": 10.0082685996
        }
      ]
    },
    {
      "GroupName": "Light",
      "GroupAminoacids": [
        {
          "TargetResidue": "K",
          "MassShift": 0.0
        },
        {
          "TargetResidue": "R",
          "MassShift": 0.0
        }
      ]
    }
  ],
  "SilacSearchNormalPeptides": false,
  "IsobaricLabelling_Search": false,
  "IsobaricLabelling_Mods": [
    {
      "MassShift": 144.1,
      "Name": "iTRAQ - 4",
      "IsCTerm": false,
      "IsNTerm": true,
      "IsVariable": false,
      "TargetResidues": "K",
      "ModIndex": 7
    },
    {
      "MassShift": 304.2022,
      "Name": "iTRAQ - 8",
      "IsCTerm": false,
      "IsNTerm": true,
      "IsVariable": false,
      "TargetResidues": "K",
      "ModIndex": 6
    },
    {
      "MassShift": 229.1629321141,
      "Name": "TMT - 6plex",
      "IsCTerm": false,
      "IsNTerm": true,
      "IsVariable": false,
      "TargetResidues": "K",
      "ModIndex": 8
    },
    {
      "MassShift": 229.1629321141,
      "Name": "TMT - 10plex",
      "IsCTerm": false,
      "IsNTerm": true,
      "IsVariable": false,
      "TargetResidues": "K",
      "ModIndex": 9
    },
    {
      "MassShift": 229.1629321141,
      "Name": "TMT - 11plex",
      "IsCTerm": false,
      "IsNTerm": true,
      "IsVariable": false,
      "TargetResidues": "K",
      "ModIndex": 10
    },
    {
      "MassShift": 304.207146,
      "Name": "TMT - 16plex (TMTpro)",
      "IsCTerm": false,
      "IsNTerm": true,
      "IsVariable": false,
      "TargetResidues": "K",
      "ModIndex": 11
    },
    {
      "MassShift": 304.207146,
      "Name": "TMT - 18plex (TMTpro)",
      "IsCTerm": false,
      "IsNTerm": true,
      "IsVariable": false,
      "TargetResidues": "K",
      "ModIndex": 12
    }
  ],
  "SelectedIsobaricLabelling_Mod": {
    "MassShift": 304.207146,
    "Name": "TMT - 16plex (TMTpro)",
    "IsCTerm": false,
    "IsNTerm": true,
    "IsVariable": false,
    "TargetResidues": "K",
    "ModIndex": 11
  },
  "IsobaricLabelling_AllowedFreeResidues": 0,
  "CalculatePairIntensities": true,
  "AddXLasVariableMod": false,
  "IsotopesInTheoreticalMS": 2,
  "MaxChargeInTheoreticalMS": 2,
  "BonusMode": true,
  "BonusScore": 0.001,
  "ApplyNeutralLossH2O": false,
  "ApplyNeutralLossNH3": false,
  "StarIntensity": 0.7,
  "FastaDistinctByLocus": true,
  "ApplyQuantileIntensityThreshold": false,
  "QuantileIntensityThreshold": 0.3
}

**Comment by diogobor** [comment]
Dear Jiale Zhao,

This error happened because the current version of Scout requires a processor with at least 4 cores to run the search. If you are using a Virtual Machine or a processor that contains less than 4 cores, Scout shows the error you pointed out.

We're optimizing the algorithm to be compatible with processors that contain less then 4 cores.

Best,
Diogo

**Comment by Heisenburger2020** [comment]
Thank you for your reply. After I added 32 cores to my virtual machine, the error won't come out. Thank you!!!
