### ISSUE TITLE
Issues when running Scout

### ISSUE THREAD

**Issue by alessiodiianni** [diogobor/Scout#3]
Hi, I am trying to test your new software on an already published BSA dataset cross-linked with DSBU (Ihling et al. 2021, Anal. Chem.). After changing the settings and selecting the .mgf file and the .fasta file, I get this error message:

################################################### |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | --
Scout - v. 1.4.10 |   |   |   |   |   |   |   |   |   |  
Engineered by Clasen et al. - LPEC / Brazil & The Liu Lab / Germany |   |   |   |   |   |   |  
################################################### |   |   |   |   |   |   |   |  
Starting run at C:\Users\MS_data\DSBU. |   |   |   |   |   |   |   |  
Database: BSA.fasta. |   |   |   |   |   |   |   |   |   |   |  
============= |   |   |   |   |   |   |   |   |   |   |   |  
Search parameters: |   |   |   |   |   |   |   |   |   |   |   |  
============= |   |   |   |   |   |   |   |   |   |   |   |  
Database file: BSA.fasta |   |   |   |   |   |   |   |   |   |   |  
Fasta batch size: 30000 |   |   |   |   |   |   |   |   |   |   |  
Raw directory: C:\Users\MS_data\DSBU |   |   |   |   |   |   |   |  
Spectra saved in the results: False |   |   |   |   |   |   |   |   |   |  
Add contaminants: True |   |   |   |   |   |   |   |   |   |   |  
Add decoys: True |   |   |   |   |   |   |   |   |   |   |   |  
Fragment bin tolarance: 0.02 |   |   |   |   |   |   |   |   |   |   |  
Fragment bin tolarance: 0 |   |   |   |   |   |   |   |   |   |   |  
Max fragment bin m/z: 1800 |   |   |   |   |   |   |   |   |   |   |  
Min fragment bin m/z: 200 |   |   |   |   |   |   |   |   |   |   |  
Deconvolution for MS Searching: False |   |   |   |   |   |   |   |   |   |  
Deconvolution for Ion Pair Searching: True |   |   |   |   |   |   |   |   |  
Cross-linker: DSBU |   |   |   |   |   |   |   |   |   |   |   |  
Mass: 196.0848 |   |   |   |   |   |   |   |   |   |   |   |  
Target N-term: True |   |   |   |   |   |   |   |   |   |   |  
Light fragment: 85.05276381 |   |   |   |   |   |   |   |   |   |   |  
Heavy fragment: 111.03202835 |   |   |   |   |   |   |   |   |   |  
Reaction residue(s): K |   |   |   |   |   |   |   |   |   |   |  
Enzyme: Trypsin |   |   |   |   |   |   |   |   |   |   |   |  
Enzyme specificity: FullySpecific |   |   |   |   |   |   |   |   |   |  
Isotopic possibilities precursor: 1 |   |   |   |   |   |   |   |   |   |  
Min peptide length: 6 |   |   |   |   |   |   |   |   |   |   |  
Max peptide length: 60 |   |   |   |   |   |   |   |   |   |   |  
Max variable modifications per peptide: 2 |   |   |   |   |   |   |   |   |  
Min peptide mass: 500 |   |   |   |   |   |   |   |   |   |   |  
Max peptide mass: 6000 |   |   |   |   |   |   |   |   |   |   |  
Max miscleavages: 3 |   |   |   |   |   |   |   |   |   |   |  
Ppm error on MS1 level: 10 |   |   |   |   |   |   |   |   |   |   |  
Ppm error on MS2 level: 20 |   |   |   |   |   |   |   |   |   |   |  
Static Modification(s): |   |   |   |   |   |   |   |   |   |   |  
1)  Name: Carbamidomethyl |   |   |   |   |   |   |   |   |   |   |  
Mass: 57.02146 |   |   |   |   |   |   |   |   |   |   |   |  
Target residues: C |   |   |   |   |   |   |   |   |   |   |  
N-term: False |   |   |   |   |   |   |   |   |   |   |   |  
C-term: False |   |   |   |   |   |   |   |   |   |   |   |  
Variable Modification(s): |   |   |   |   |   |   |   |   |   |   |  
1)  Name: Oxidation of Methionine |   |   |   |   |   |   |   |   |   |  
Mass: 15.9949 |   |   |   |   |   |   |   |   |   |   |   |  
Target residues: M |   |   |   |   |   |   |   |   |   |   |  
N-term: False |   |   |   |   |   |   |   |   |   |   |   |  
C-term: False |   |   |   |   |   |   |   |   |   |   |   |  
=================== |   |   |   |   |   |   |   |   |   |   |  
Post processing parameters: |   |   |   |   |   |   |   |   |   |   |  
=================== |   |   |   |   |   |   |   |   |   |   |  
Use only unique XLs into PPIs: False |   |   |   |   |   |   |   |   |   |  
Separate protein intra- and inter-crosslinks: True |   |   |   |   |   |   |   |   |  
FDR: |   |   |   |   |   |   |   |   |   |   |   |   |  
CSM level: 0.01 |   |   |   |   |   |   |   |   |   |   |   |  
Residue pair level: 0.01 |   |   |   |   |   |   |   |   |   |   |  
PPI level: 0.01 |   |   |   |   |   |   |   |   |   |   |   |  
=============== |   |   |   |   |   |   |   |   |   |   |   |  
INFO: Starting search... |   |   |   |   |   |   |   |   |   |   |  
=============== |   |   |   |   |   |   |   |   |   |   |   |  
ERROR: It's not possible to read C:\Users\MS_data\DSBU\BSA_DSBU25_1.mgf |   |   |   |  
ERROR - PerformSearch method: It's not possible to assemble the search pack. |   |   |   |   |   |  
at ScoutCore.QueryLogic.SearchPackFactory.AssembleSearchPack(String rawFile | ScoutParameters parameters) |   |   |   |   |   |   |   |   |   |  
at ScoutCore.PSMEngines.Tripper.Tripper.PerformSearch(String fastaFile | String rawFile) |   |   |   |   |   |   |   |   |   |   |  
Input string was not in a correct format. |   |   |   |   |   |   |   |   |   |  
ERROR - SearchFile method: It's not possible to perform search with the file: C:\Users\MS_data\DSBU\BSA_DSBU25_1.mgf.
at ScoutCore.PSMEngines.Tripper.Tripper.PerformSearch(String fastaFile | String rawFile) |   |   |   |   |   |   |   |   |   |   |  
at ScoutCore.ScoutEngine.SearchFile(String rawFile | String fastaFile) |   |   |   |   |   |   |   |   |   |   |  
at ScoutCore.QueryLogic.SearchPackFactory.AssembleSearchPack(String rawFile | ScoutParameters parameters) |   |   |   |   |   |   |   |   |   |  
at ScoutCore.PSMEngines.Tripper.Tripper.PerformSearch(String fastaFile | String rawFile) |   |   |   |   |   |   |   |   |   |   |  
Input string was not in a correct format.

My PC has 20 logical cores and 32 GB RAM. Could you help me out with this??

**Comment by diogobor** [comment]
Hello,

The issue happened when Scout tried to read the mgf file. This file contains a different pattern for precursor mass.
We fixed the mgf reader, and we will release a new version of Scout soon.

Meanwhile, you can use the Bruker Raw file (.d) to perform your search.

Best,
Diogo

**Comment by alessiodiianni** [comment]
I tried to use also the .d file Bruker folder but it gives me similar troublesOn Jan 30, 2024, at 18:32, Diogo Borges ***@***.***> wrote:﻿
Hello,
The issue happened when Scout tried to read the mgf file. This file contains a different pattern for precursor mass.
We fixed the mgf reader, and we will release a new version of Scout soon.
Meanwhile, you can use the Bruker Raw file (.d) to perform your search.
Best,
Diogo

**Comment by diogobor** [comment]
Hello,
Ok. We fixed this issue for Bruker files (and mgf).
The next version will be released soon.

Best,
Diogo
