### ISSUE TITLE
multi-cv FAIMS runs

### ISSUE THREAD

**Issue by grandrea** [diogobor/Scout#4]
hello,

I have crosslinking MS acquisitions performed with multiple control voltages on FAIMS device. Should i split the raw files by FAIMS CV? I am asking this because if Scout makes use of MS1retention time information then the chromatogram in the MS1 will be discontinuous as the instrument switches between voltages. How do you process such data?

many thanks!

**Comment by diogobor** [comment]
Hello,

Scout uses only the precursor m/z and precursor charge to identify the candidates.
However, if you are interested to quantify the cross-linked peptides by using XIC, it would be better to split the RAW files.

Best,
Diogo

**Comment by grandrea** [comment]
thanks!
