### ISSUE TITLE
Enhancements: Minor workflow features

### ISSUE THREAD

**Issue by FriedLabJHU** [diogobor/Scout#5]
Thank you for this great tool! I heard about it at US HUPO and have been enjoying using it since.
There are a few enhancements I would like to see as a user:

1. Add a "Stop" button that is separate from a "Quit" option.
When I start a run and I realize I added the incorrect RAW files or set the incorrect parameters I have to close the whole application when I rather just stop the current run, adjust, and restart.

2. Add an "Apply" button to the Search Parameters
This is more of a psycological enhancement that would increase a user's confidence when using your tool. I _feels_ better when I press "Apply" and then say "Yes" to Accept Changes? Rather than hitting "Close" on the window and then saying "Yes" to Accept Changes?

3. Add an "Output Folder" directory selection to "Select a directory to save result files"

4. Move "Export Log" to the File menu bar

5. Make "Parameters" its own menu bar option

6. Place "Post Processing" inside "Parameters" to simplify the application

-Edgar

**Comment by diogobor** [comment]
Hello Edgar,

Thanks for your feedback.
We have taken note to improve the usability of scout for the next release version.

Best,
Diogo

**Comment by diogobor** [comment]
Hi Edgar,
We have implemented almost all points you suggested in this thread.

Thanks for evaluating and using the software.

Best,
Diogo
